### ISSUE TITLE
Wildcard For Directory Contents

### ISSUE THREAD

**Issue by jbh** [horochx/deploy-via-scp#1]
Is there some way to pass a wildcard, so that the contents of the directory are copied over, rather than the entire directory? For example:

```yaml
name: Test SCP

on: [push]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Deploy
      uses: horochx/deploy-via-scp@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        local: "dist/recipes/*"
        remote: ${{ secrets.REMOTE }}
```

This fails currently. Or is there some other solution to achieve this?
