### ISSUE TITLE
Can I use with "local: ." ?

### ISSUE THREAD

**Issue by bartier** [horochx/deploy-via-scp#2]
Is it possible to use with `local: .` in my workflow?
 
```
    - uses: actions/checkout@v2
    - uses: horochx/deploy-via-scp@master
      with:
        local: .
        remote: /home/${{ secrets.PRD_USERNAME }}/folder/
        host: ${{ secrets.PRD_HOST }}
        port: ${{ secrets.PRD_SSH_PORT }}
        user: ${{ secrets.PRD_USERNAME }}
        key: ${{ secrets.PRD_PRIVATE_KEY }}
```

I got an error and I'm not sure if this is possible.
